---
# Example Playbook: cisco.ucs.ucs_vlan_find
- hosts: ucs
  connection: local
  gather_facts: false

  tasks:
    - name: Test that we have a UCS hostname, UCS username, and UCS password
      fail:
        msg: 'Please define the following variables: ucs_hostname, ucs_username and ucs_password.'
      when: ucs_hostname is not defined or ucs_username is not defined or ucs_password is not defined
      vars:
        # use "<<: *login_info" to substite the information below in each task
        # this is not required, however it makes the playbook shorter.
        login_info: &login_info
          hostname: "{{ ucs_hostname }}"
          username: "{{ ucs_username }}"
          password: "{{ ucs_password }}"

    - name: Get all vlans in fabric A
      cisco.ucs.ucs_vlan_find:
        <<: *login_info
        fabric: 'common'
        pattern: '.'
      register: response

    - name: show response
      debug:
        msg: "{{ response }}"

    - name: Confirm if vlan 15 is present
      cisco.ucs.ucs_vlan_find:
        <<: *login_info
        vlanid: '200'
      register: response

    - name: show response
      debug:
        msg: "{{ response }}"
