---
# Example Playbook: cisco.ucs.ucs_ip_pool
- hosts: ucs
  connection: local
  gather_facts: false

  tasks:
    - name: Test that we have a UCS hostname, UCS username, and UCS password
      fail:
        msg: 'Please define the following variables: ucs_hostname, ucs_username and ucs_password.'
      when: ucs_hostname is not defined or ucs_username is not defined or ucs_password is not defined
      vars:
        # use "<<: *login_info" to substite the information below in each task
        # this is not required, however it makes the playbook shorter.
        login_info: &login_info
          hostname: "{{ ucs_hostname }}"
          username: "{{ ucs_username }}"
          password: "{{ ucs_password }}"

    - name: Add UCS Organization
      cisco.ucs.ucs_org:
        <<: *login_info
        org_name: level1
        parent_org_path: root
        description: level1 org
        state: present
        delegate_to: localhost

    - name: Configure IPv4 and IPv6 address pool
      cisco.ucs.ucs_ip_pool:
        <<: *login_info
        name: ip-pool-01
        org_dn: org-root/org-level1
        ipv4_blocks:
        - first_addr: 192.168.10.1
          last_addr: 192.168.10.20
          subnet_mask: 255.255.255.128
          default_gw: 192.168.10.2
        - first_addr: 192.168.11.1
          last_addr: 192.168.11.20
          subnet_mask: 255.255.255.128
          default_gw: 192.168.11.2
        ipv6_blocks:
        - ipv6_first_addr: fe80::1cae:7992:d7a1:ed07
          ipv6_last_addr: fe80::1cae:7992:d7a1:edfe
          ipv6_default_gw: fe80::1cae:7992:d7a1:ecff
        - ipv6_first_addr: fe80::1cae:7992:d7a1:ec07
          ipv6_last_addr: fe80::1cae:7992:d7a1:ecfe
          ipv6_default_gw: fe80::1cae:7992:d7a1:ecff

    - name: Remove IPv4 and IPv6 address pool blocks
      cisco.ucs.ucs_ip_pool:
        <<: *login_info
        name: ip-pool-01
        org_dn: org-root/org-level1
        ipv4_blocks:
        - first_addr: 192.168.10.1
          last_addr: 192.168.10.20
          state: absent
        ipv6_blocks:
        - ipv6_first_addr: fe80::1cae:7992:d7a1:ec07
          ipv6_last_addr: fe80::1cae:7992:d7a1:ecfe
          state: absent

    - name: Remove IPv4 and IPv6 address pool
      cisco.ucs.ucs_ip_pool:
        <<: *login_info
        name: ip-pool-01
        org_dn: org-root/org-level1
        state: absent

    - name: Remove UCS Organization
      cisco.ucs.ucs_org:
        <<: *login_info
        org_name: level1
        parent_org_path: root
        state: absent
        delegate_to: localhost
