---
# Example Playbook: cisco.ucs.ucs_storage_profile
- hosts: ucs
  connection: local
  gather_facts: false

  tasks:
    - name: Test that we have a UCS hostname, UCS username, and UCS password
      fail:
        msg: 'Please define the following variables: ucs_hostname, ucs_username and ucs_password.'
      when: ucs_hostname is not defined or ucs_username is not defined or ucs_password is not defined
      vars:
        # use "<<: *login_info" to substite the information below in each task
        # this is not required, however it makes the playbook shorter.
        login_info: &login_info
          hostname: "{{ ucs_hostname }}"
          username: "{{ ucs_username }}"
          password: "{{ ucs_password }}"

    - name: Add UCS Organization
      cisco.ucs.ucs_org:
        <<: *login_info
        org_name: level1
        parent_org_path: root
        description: level1 org
        state: present
        delegate_to: localhost

    - name: Configure Storage Profile
      cisco.ucs.ucs_storage_profile:
        <<: *login_info
        name: DEE-StgProf
        org_dn: org-root/org-level1
        local_luns:
        - name: Boot-LUN
          size: '60'
          disk_policy_name: DEE-DG
        - name: Data-LUN
          size: '200'
          disk_policy_name: DEE-DG

    - name: Remove Local LUN from Storage Profile
      cisco.ucs.ucs_storage_profile:
        <<: *login_info
        name: DEE-StgProf
        org_dn: org-root/org-level1
        local_luns:
        - name: Data-LUN
          state: absent

    - name: Remove Storage Profile
      cisco.ucs.ucs_storage_profile:
        <<: *login_info
        name: DEE-StgProf
        org_dn: org-root/org-level1
        state: absent

    - name: Remove UCS Organization
      cisco.ucs.ucs_org:
        <<: *login_info
        org_name: level1
        parent_org_path: root
        state: absent
        delegate_to: localhost
