---
# Example Playbook: cisco.ucs.ucs_system_qos
- hosts: ucs
  connection: local
  gather_facts: false

  tasks:
    - name: Test that we have a UCS hostname, UCS username, and UCS password
      fail:
        msg: 'Please define the following variables: ucs_hostname, ucs_username and ucs_password.'
      when: ucs_hostname is not defined or ucs_username is not defined or ucs_password is not defined
      vars:
        # use "<<: *login_info" to substite the information below in each task
        # this is not required, however it makes the playbook shorter.
        login_info: &login_info
          hostname: "{{ ucs_hostname }}"
          username: "{{ ucs_username }}"
          password: "{{ ucs_password }}"

    - name: Check QoS System Class
      cisco.ucs.ucs_system_qos:
        <<: *login_info
        priority: platinum
        cos: '5'
        weight: '10'
      delegate_to: localhost
      check_mode: true

    - name: Add QoS System Class
      cisco.ucs.ucs_system_qos:
        <<: *login_info
        priority: platinum
        cos: '5'
        weight: '10'
      delegate_to: localhost

    - name: Idempotent Add QoS System Class
      cisco.ucs.ucs_system_qos:
        <<: *login_info
        priority: platinum
        cos: '5'
        weight: '10'
      delegate_to: localhost

    - name: Check Update QoS System Class
      cisco.ucs.ucs_system_qos:
        <<: *login_info
        priority: platinum
        cos: '5'
        weight: '10'
        mtu: '9216'
      delegate_to: localhost
      check_mode: true

    - name: Update QoS System Class
      cisco.ucs.ucs_system_qos:
        <<: *login_info
        priority: platinum
        cos: '5'
        weight: '10'
        mtu: '9216'
      delegate_to: localhost

    - name: Idempotent Update QoS System Class
      cisco.ucs.ucs_system_qos:
        <<: *login_info
        priority: platinum
        cos: '5'
        weight: '10'
        mtu: '9216'
      delegate_to: localhost
