---
# Example Playbook: cisco.ucs.ucs_query
- hosts: ucs
  connection: local
  gather_facts: false

  tasks:
    - name: Test that we have a UCS hostname, UCS username, and UCS password
      fail:
        msg: 'Please define the following variables: ucs_hostname, ucs_username and ucs_password.'
      when: ucs_hostname is not defined or ucs_username is not defined or ucs_password is not defined
      vars:
        # use "<<: *login_info" to substite the information below in each task
        # this is not required, however it makes the playbook shorter.
        login_info: &login_info
          hostname: "{{ ucs_hostname }}"
          username: "{{ ucs_username }}"
          password: "{{ ucs_password }}"

    - name: Query UCS Class ID
      cisco.ucs.ucs_query:
        <<: *login_info
        class_ids: computeBlade
        delegate_to: localhost
      register: response

    - name: show response
      debug:
        msg: "{{ response }}"
        
    - name: Query UCS Class IDs
      cisco.ucs.ucs_query:
        <<: *login_info
        class_ids: computeBlade, fabricVlan
        delegate_to: localhost
      register: response

    - name: show response
      debug:
        msg: "{{ response }}"
    
    - name: Query UCS Distinguished Name
      cisco.ucs.ucs_query:
        <<: *login_info
        distinguished_names: org-root
        delegate_to: localhost
      register: response

    - name: show response
      debug:
        msg: "{{ response }}"
    
    - name: Query UCS Distinguished Names
      cisco.ucs.ucs_query:
        <<: *login_info
        distinguished_names: org-root, sys/rack-unit-1, sys/chassis-1/blade-2
        delegate_to: localhost
      register: response

    - name: show response
      debug:
        msg: "{{ response }}"